version: 2.1

workflows:
  build-test:
    jobs:
      - prep-deps
      - test-build:
          requires:
            - prep-deps
      - test-lint:
          requires:
            - prep-deps
            - test-build
      - test-unit:
          requires:
            - prep-deps
            - test-build
      - all-tests-pass:
          requires:
            - test-build
            - test-lint
            - test-unit

jobs:
  prep-deps:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install main package deps
          command: |
            .circleci/scripts/deps-install.sh
      - run:
          name: Install example deps
          command: |
            .circleci/scripts/examples-deps-install.sh
      - run:
          name: Collect yarn install HAR logs
          command: |
            .circleci/scripts/collect-har-artifact.sh
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - build-artifacts
            - examples/*/node_modules

  test-build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  test-lint:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn lint

  test-unit:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Unit tests
          command: yarn test:nobuild

  all-tests-pass:
    docker:
      - image: circleci/node:10
    steps:
      - run:
          name: All tests passed
          command: echo 'Great success'
